apiVersion: v2
description: airflow is a platform to programmatically author, schedule, and monitor workflows
name: airflow
version: 7.16.0
appVersion: 1.10.12
icon: https://airflow.apache.org/_images/pin_large.png
home: https://airflow.apache.org/
dependencies:
- name: postgresql
  version: 8.6.4
  repository: https://charts.helm.sh/stable
  condition: postgresql.enabled
- name: redis
  version: 10.5.7
  repository: https://charts.helm.sh/stable
  condition: redis.enabled
maintainers:
  - name: gsemet
    url: https://github.com/gsemet
  - name: thesuperzapper
    url: https://github.com/thesuperzapper
sources:
  - https://github.com/airflow-helm/charts/tree/main/charts/airflow
keywords:
  - airflow
  - dag
  - workflow
